version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: schoolstaff_db
    environment:
      - POSTGRES_USER=schoolstaff
      - POSTGRES_PASSWORD=schoolstaff123
      - POSTGRES_DB=SchoolStaffDB
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 