@host = http://localhost:5225/api

### Login
POST {{host}}/user/login
Content-Type: application/json

{
  "email": "test@123.com",
  "password": "YourSecurePassword123!"
}

### Register new user (requires admin token)
POST {{host}}/user/register
Content-Type: application/json
Authorization: Secret {{secret}}

{
  "firstName": "Richard",
  "lastName": "Kotch",
  "dateOfBirth": "01-01-1963",
  "phoneNumber": "555-555-1234",
  "email": "test@123.com",
  "password": "YourSecurePassword123!"
}
